# Generated by Django 4.2.5 on 2023-09-11 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookModel",
            new_name="Books",
        ),
    ]
