# Generated by Django 4.2.5 on 2023-09-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_rename_bookmodel_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="inventory",
            field=models.IntegerField(),
        ),
    ]
