# Generated by Django 4.2.5 on 2023-09-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0004_borrowing_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING ", "Pending"), ("PAID", "Paid")],
                        default="PENDING ",
                        max_length=25,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PAYMENT  ", "Payment"), ("FINE", "Fine")],
                        default="PAYMENT  ",
                        max_length=25,
                    ),
                ),
                ("session_url", models.URLField()),
                ("session_id", models.CharField(max_length=255)),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowings.borrowing",
                    ),
                ),
            ],
        ),
    ]
